image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

environment:
  matrix:
    - COMPILER: Visual Studio 14 2015
      ARCHITECTURE: x64
    - COMPILER: Visual Studio 14 2015
      ARCHITECTURE: Win32
    - COMPILER: Visual Studio 15 2017
      ARCHITECTURE: x64
    - COMPILER: Visual Studio 15 2017
      ARCHITECTURE: Win32
    - COMPILER: Visual Studio 16 2019
      ARCHITECTURE: x64
    - COMPILER: Visual Studio 16 2019
      ARCHITECTURE: Win32

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake .. -G "%COMPILER%" -A %ARCHITECTURE%
  - cmake --build . --config %CONFIGURATION%
